version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install -g aws-cdk
      - npm install
  build:
    commands:
      - npm run lint         # ESLint 実行
      - npm run build        # TypeScript ビルド
      - cdk synth            # CDK 合成
artifacts:
  files:
    - '**/*'
  base-directory: cdk.out