version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - node -v
      - npm -v
      - npm install -g aws-cdk
      - npm install -g npm@11
      - npm ci
      - npm audit fix
      - pip install semgrep  # ← Semgrepをインストール
  build:
    commands:
      - npx eslint . --ext .ts,.tsx
      - semgrep --config=auto .  # ← Semgrep実行（自動ルール）
      - npm run build
      - npm test
      - npx cdk synth
artifacts:
  files:
    - '**/*'
  base-directory: cdk.out